books/urls.py
from django.urls import path
from .views import list_books, create_book, update_book, delete_book, view_book, graph

urlpatterns = [
    path('', list_books, name='list_books'),
    path('new', create_book, name='create_books'),
    path('update/<int:id>/', update_book, name='update_book'),
    path('delete/<int:id>/', delete_book, name='delete_book'),
	path('view/<int:id>', view_book, name='view_book'),
 	path('graph/', graph, name='graph'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path('', include(('users.urls', 'users'), namespace='users')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
    path('books/auth/', include('rest_framework.urls')),
    path('books/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('books/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

users/urls.py
from django.urls import path
from .views import do_login, do_logout, create_user, update_user

urlpatterns = [
    path('', do_login, name='login'),
    path('logout', do_logout, name='logout'),
    path('register', create_user, name='register'),
    path('update/<int:id>/', update_user, name='update_user'),
]

books/models.py
from django.db import models
    
class Book(models.Model):
    name = models.CharField(max_length=60)
    author = models.CharField(max_length=60)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.description

users/models.py
from django.db import models

# Create your models here.

books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'price', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 8}),
        }

users/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

class UserModelForm(forms.ModelForm):
    User._meta.get_field('first_name').blank = False
    User._meta.get_field('email').blank = False
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength':100}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength':60}),
        }

    def save(self, commit=True):
        user = super(UserModelForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

books/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from .models import Book
from .forms import BookForm
from matplotlib import pyplot as plt
import io
import base64


@login_required
def list_books(request):
    # Search
    search = request.GET.get('search')
    if search:
       books = Book.objects.filter(Q(name__icontains=search))
    else:
       books = Book.objects.all()

    # Order
    sort = request.GET.get('sort')
    order = request.GET.get('order')
    if sort:
        if order == 'asc':
           books = Book.objects.order_by(sort)
        else:
           books = Book.objects.order_by(sort).reverse()

    # Pagination
    paginator = Paginator(books, 5)
    page = request.GET.get('page')

    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)

    return render(request, 'books.html', {'books': books, 'page': page})

@login_required
def create_book(request):
    form = BookForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('list_books')

    return render(request, 'books-form.html', {'form': form})

@login_required
def update_book(request, id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, instance=book)

    if form.is_valid():
        form.save()
        return redirect('list_books')

    return render(request, 'books-form.html', {'form': form, 'book': book})

@login_required
def delete_book(request, id):
    book = Book.objects.get(id=id)
    book.delete()

    return redirect('list_books')

def view_book(request, id):
    book = Book.objects.get(id=id)

    return render(request, 'book-detail.html', {'book': book})



def graph(request):
    books = Book.objects.all()

    names = [book.name for book in books]
    prices = [book.price for book in books]
    fig, ax = plt.subplots()


    ax.set_title('Book Prices')
    ax.set_xlabel('Names')
    ax.set_ylabel('Prices')


    # # Create the bar graph
    plt.bar(names, prices)

    # Convert the plot to a binary string and get its mime type
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    string = base64.b64encode(buf.read()).decode()
    mime_type = 'image/png'

    # Return the data to the HTML template
    return render(request, 'graph.html', {'data': string, 'mime_type': mime_type})

users/views.py
from django.shortcuts import render, redirect
from users.forms import UserModelForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def create_user(request):
    form = UserModelForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/books')
    return render(request, 'register.html', {'form': form})

@login_required
def update_user(request, id):
    user = User.objects.get(id=id)
    form = UserModelForm(request.POST or None, instance=user)

    if form.is_valid():
        form.save()
        return redirect('/books')

    return render(request, 'users-form.html', {'form': form, 'user': user})

def do_login(request):
    form = UserModelForm(request.POST or None)
    error = ''

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                try:
                    login(request, user)
                    return redirect('/books')
                except:
                    error = 'Internal error'
            else:
                error = 'Inactive user'
        else:
            error = 'Invalid username or password!'

    return render(request, 'login.html', {'form': form, 'error': error})

def do_logout(request):
    logout(request)
    return redirect('/')

books/templates/book-detail.html
{% extends 'layouts/base.html' %}
{% load sortable_column %}
{% block content %}
	<h2>Book</h2>
	<div class="panel panel-default">
		<div class="panel-body">
			<p><strong>Name:</strong> {{ book.name }}</p>
			<p><strong>Author:</strong> {{ book.author }}</p>
			<p><strong>Price:</strong> {{ book.price }}</p>
			<p><strong>Description:</strong><br>
			{{ book.description }}</p>
			<br><br>
			<a href="/books" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Back</a>
			<a href="{% url 'update_book' book.id %}" class="btn btn-success"><i class="fa fa-edit"></i> Edit</a>
		</div>
	</div>
{% endblock %}

books/templates/books-form.html
{% extends 'layouts/base.html' %}
{% load bootstrap %}
{% block content %}
	{% if book %}
		<h2>Update Book</h2>
	{% else %}
		<h2>New Book</h2>
	{% endif %}

  <div class="panel panel-default">
  	<div class="panel-body">
  		<div class="container-form col-sm-5">
        <form method="POST" novalidate>
            {% csrf_token %}
            {{ form|bootstrap }}
            <a href="/books" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Back</a>
			<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

books/templates/books.html
{% extends 'layouts/base.html' %}
{% load sortable_column %}
{% block content %}
	<h2>List Books</h2>
	<a href="{% url 'create_books' %}" class="btn btn-success"><i class="fa fa-plus"></i> New Book</a>
	<div class="search-right">
		<form method="GET" action="">
			<input type="text" name="search" value="{{request.GET.search}}" class="form-control" placeholder="Search">
			<button type="submit" class="btn btn-primary">
				<i class="fa fa-search"></i>
			</button>
		</form>
	</div>
	{% if books|length == 0 %}
		<div class="alert alert-info">No items registered</div>
	{% else %}
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					{% sortable_column request=request property="name" title="Name" default_order="asc" %}
					{% sortable_column request=request property="author" title="Author" %}
					{% sortable_column request=request property="price" title="Price" %}
					<th class="col-actions">Actions</th>
				</tr>
			</thead>
			<tbody>
			{% for book in books %}
				<tr>
					<td>{{ book.name }}</td>
					<td>{{ book.author }}</td>
					<td>{{ book.price }}</td>
					<td class="text-center"><a href="{% url 'view_book' book.id %}" class="btn btn-default"><i class="fa fa-eye"></i> View</a>
					<a href="{% url 'update_book' book.id %}" class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
					<a href="{% url 'delete_book' book.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?')"><i class="fa fa-trash"></i> Delete</a></td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<div class="pag-right">
			{% include 'pagination.html' with page=books %}
		</div>
	{% endif %}
{% endblock %}

books/templates/graph.html
<!DOCTYPE html>
<html>
<head>
    <title>Graph</title>
</head>
<body>
    <h1>Graph</h1>
    <img src="data:{{ mime_type }};base64,{{ data }}" alt="Graph">
</body>
</html>

books/templates/pagination.html
<ul class="pagination">
  {% if page.has_previous %}
	<li class="prev">
		<a rel="prev" href="?page=1">← First</a>
	</li>
  {% endif %}
 
  {% for num in page.paginator.page_range %}
	
	{% if page.number == num %}
	<li class="active">
		<span>{{ num }}</span>
	</li>
	{% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
	<li>
		<a rel="next" href="?page={{ num }}">{{ num }}</a>
	</li>
	{% endif %}
 
  {% endfor %}
	
  {% if page.has_next %}
	<li class="next">
		<a rel="next" href="?page={{ page.paginator.num_pages }}">Last →</a>
	</li>
	{% endif %}
</ul>

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/pagination.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
	
	<title>Books</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-header">
        <div class="navbar-header">
          <!-- Collapsed Hamburger -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Branding Image -->
          <a class="navbar-brand" href="/books">
            <strong>Books</strong>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
          <!-- Left Side Of Navbar -->
          <!-- <ul class="nav navbar-nav">
            <li class="nav-item">Link1</li>
            <li class="nav-item">Link2</li>
            <li class="nav-item">Link3</li>
          </ul> -->

          <!-- Right Side Of Navbar -->
          <ul class="nav navbar-nav navbar-right">
            <!-- Authentication Links -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <img src="{% static 'img/avatar-placeholder.svg' %}" alt="" width="30" class="img-circle">
                    {{ user.get_username }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'users:update_user' request.user.id %}">Edit Profile</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/layouts/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">

	<title>Books</title>
</head>
<body class="page-login">
    <div class="bg-login">
      <div class="container-login">
          {% block content %}
          {% endblock %}
      </div>
    </div>
    
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/login.html
{% extends 'layouts/login.html' %}
{% load bootstrap %}
{% block content %}
  <form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    <div class="panel">
    	<div class="panel-body box-login">
        <h3 class="title-login">Sign in</h3>
        <div class="form-group">
          <label for="username" class="sr-only">Username</label>
          <span class="fa fa-user"></span>
          <input type="text" name="username" class="form-control input-login" placeholder="Username" required autofocus>
        </div>
        <div class="form-group">
          <label for="password" class="sr-only">Password</label>
          <span class="fa fa-lock"></span>
          <input type="password" name="password" class="form-control input-login" placeholder="Password" required>
        </div>
        <div class="form-group">
          <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
        </div>
        <a href="{% url 'users:register' %}" class="link-register">Create an account</a>
    		{% if error %}
    			<div class="alert alert-danger">{{error}}</div>
    		{% endif %}
      </div>
    </div>
    <div class="text-center">
      <strong>Test Login:</strong><br><br>
      Username: admin<br>
      Password: admin<br>
    </div>
  </form>
{% endblock %}

users/templates/register.html
{% extends 'layouts/login.html' %}
{% load bootstrap %}
{% block content %}
<div class="panel">
	<div class="panel-body">
		<h3 class="title-login">Sign Up</h3>
		<form method="POST">
		  {% csrf_token %}
		  {{ form|bootstrap }}
		  <a href="/" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Back</a>
			<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
		</form>
	</div>
</div>
{% endblock %}

users/templates/users-form.html
{% extends 'layouts/base.html' %}
{% load bootstrap %}
{% block content %}
<h2>Edit Profile</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<form method="POST" novalidate>
				{% csrf_token %}
				{{ form|bootstrap }}
				<a href="/books" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Back</a>
				<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Save</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}